### ISSUE TITLE
Does not with NA?

### ISSUE THREAD

**Issue by sihanding** [Zelazny7/onehot#3]
Hi,

Perhaps I did something wrong, but it seems that it does not work with NAs...

Here is what I have done:

install.packages("onehot")
library("onehot")
#### Am I installing the correct package? As this is the package from Cran.

getOption("na.action")
[1] "na.omit"

## Create a simple data frame
number = data.frame(x = c(NA, NA, "apple", "apple", "banana", "banana", "peer", "peer"), 
                    y = c("a", "a", "b", "b", "c", "c", NA, NA))
encode = onehot(number, addNA = TRUE, max_levels = 5)
number = as.data.frame(predict(encode, number))
### See the outcome
number

  x=apple x=banana x=peer x=NA y=a y=b y=c y=NA
       0        0      0    0   1   0   0    0
       0        0      0    0   1   0   0    0
       1        0      0    0   0   1   0    0
       1        0      0    0   0   1   0    0
       0        1      0    0   0   0   1    0
       0        1      0    0   0   0   1    0
       0        0      1    0   0   0   0    0
       0        0      1    0   0   0   0    0

Note that in column 4 (i.e., "x=NA"), the values are all 0, instead of having first two rows being 1, as it corresponds to NAs.

Thank you in advance!

Best regards,
Sihan

**Comment by Zelazny7** [comment]
The package on github is many commits ahead of the one on CRAN. Sorry for the inconvenience. The best way to resolve this is to use `devtools::install_git` to install the github version on your machine. I have not yet had the time to get this version onto CRAN.

**Comment by sihanding** [comment]
Right, clear. 
Thanks a lot!
